use_frameworks!

target 'BRouter_Example' do
  pod 'BRouter', :path => '../'

  target 'BRouter_Tests' do
    inherit! :search_paths

    #pod 'Quick', '~> 1.2.0'
    #pod 'Nimble', '~> 7.0.2'
  end
end
